# Uncomment this file to enable multilanguage site support

[en]
languageName = "EN"
languagedirection = "ltr"
title = "Jongwook's dev blog"
weight = 1

[ko]
languageName = "KR"
languagedirection = "ltr"
title = "종욱의 개발 블로그"
weight = 2
