# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/JeonJongYook"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "instagram"
url = "https://instagram.com/w._.hddnr_0121/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "notion"
name = "notion"
url = "https://junjonguk.notion.site/Hello-My-name-is-JeonJongWook-490b3b38af054f56ae9f9b7660ce0923"

[social.params]
icon = "brand-notion"


